services:
  postgres:
    container_name: postgres_database
    image: postgres:17.7
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - database_network
  
  mongo:
    image: mongo:7
    container_name: mongo-standalone
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - database_network

  

volumes:
  database_volume:
    name: ${DB_VOLUME}
  mongo_data:

networks:
  database_network:
    name: database_network